/*
 * 配置自定义菜单
 */
"use strict"
 
module.exports = {
  "button":[
  {
    "name":"好陪护",
    "sub_button":[
        {
          "name":"找护工",
          "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/findWork"
        },
        {
          "name":"好陪护",
          "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/findWork"
        },
        {
            "name":"搜索",
            "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/findWork"
          }
    ]
  },
  {
    "name":"更多服务",
    "sub_button":[
      {
        "name":"医院向导",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/login"
      },
      {
        "name":"最新活动",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/login"
      },
      {
        "name":"资讯",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/login"
      }
    ]
  },
  {
    "name":"我的",
    "sub_button":[
      {
        "name":"关于我们",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/me"
      },
      {
        "name":"我的订单",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/me"
      },
      {
        "name":"优惠券",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/me"
      },
      {
        "name":"钱包",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/me"
      },
      {
        "name":"个人中心",
        "type":"view",
            "url":"http://mfc123.xicp.io/customer.html#/me"
      }
    ]
  }]
}
